module.exports = app => {
  const values = {
    sub10: [
      {
        count_max: '',
        item_count_status: 'Active',
        method: '',
        collection_max: '15',
        item_count: '0',
        sysdb_path: '/oper/ipv4-acl/gl/show/access-list/*/sequencetable/*',
        total_send_errors: '0',
        last_collection_start: '2018-04-25 21:02:35.2535393419 +0000',
        total_min: '2',
        collection_interval: '10000',
        count: '',
        total_other_errors: '0',
        total_avg: '3',
        num_collection: '16',
        encoding_collection: 'self-describing-gpb',
        total_max: '15',
        missed_collections_dropped_bytes: '0',
        missed_collections_send_packets: '0',
        collection_id: '8',
        total_deferred: '0',
        count_min: '',
        total_send_drops: '0',
        no_data_instances: '0',
        collection_min: '2',
        last_collection_end: '2018-04-25 21:02:35.2535396419 +0000',
        missed_collections_send_bytes: '0',
        count_avg: '',
        sensor_path_collection:
          'Cisco-IOS-XR-ipv4-acl-oper:ipv4-acl-and-prefix-list/access-list-manager/accesses/access/access-list-sequences/access-list-sequence',
        missed_collections: '0'
      }
    ],
    sub15: [
      {
        count_max: '196',
        item_count_status: 'Active',
        method: 'DATALIST',
        collection_max: '196',
        item_count: '106',
        sysdb_path: '/oper/intf_mgbl/gl/full/*',
        total_send_errors: '0',
        last_collection_start: '2018-04-25 21:02:37.2537690419 +0000',
        total_min: '125',
        collection_interval: '10000',
        count: '15',
        total_other_errors: '0',
        total_avg: '147',
        num_collection: '15',
        encoding_collection: 'self-describing-gpb',
        total_max: '196',
        missed_collections_dropped_bytes: '0',
        missed_collections_send_packets: '15',
        collection_id: '9',
        total_deferred: '0',
        count_min: '125',
        total_send_drops: '0',
        no_data_instances: '0',
        collection_min: '125',
        last_collection_end: '2018-04-25 21:02:38.2537818419 +0000',
        missed_collections_send_bytes: '236436',
        count_avg: '146',
        sensor_path_collection:
          'Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-xr/interface',
        missed_collections: '0'
      }
    ],
    sub4: [
      {
        count_max: '162',
        item_count_status: 'Active',
        method: 'DATALIST',
        collection_max: '162',
        item_count: '4249',
        sysdb_path: '/oper/lpts_pifib_edm/node/*/by-type/*/*',
        total_send_errors: '0',
        last_collection_start: '2018-04-25 21:02:07.2506790419 +0000',
        total_min: '110',
        collection_interval: '10000',
        count: '12',
        total_other_errors: '12',
        total_avg: '129',
        num_collection: '12',
        encoding_collection: 'self-describing-gpb',
        total_max: '176',
        missed_collections_dropped_bytes: '0',
        missed_collections_send_packets: '48',
        collection_id: '6',
        total_deferred: '0',
        count_min: '100',
        total_send_drops: '0',
        no_data_instances: '0',
        collection_min: '100',
        last_collection_end: '2018-04-25 21:02:07.2506906419 +0000',
        missed_collections_send_bytes: '2625870',
        count_avg: '118',
        sensor_path_collection:
          'Cisco-IOS-XR-lpts-pre-ifib-oper:lpts-pifib/nodes/node/type-values/type-value/entry',
        missed_collections: '0'
      }
    ],
    sub13: [
      {
        count_max: '10237',
        item_count_status: 'Active',
        method: 'DATALIST',
        collection_max: '10237',
        item_count: '28',
        sysdb_path: '/oper/filesystem/gl/*',
        total_send_errors: '0',
        last_collection_start: '2018-04-25 21:02:07.2506892419 +0000',
        total_min: '795',
        collection_interval: '10000',
        count: '9',
        total_other_errors: '0',
        total_avg: '3347',
        num_collection: '9',
        encoding_collection: 'self-describing-gpb',
        total_max: '10238',
        missed_collections_dropped_bytes: '0',
        missed_collections_send_packets: '9',
        collection_id: '2',
        total_deferred: '0',
        count_min: '794',
        total_send_drops: '0',
        no_data_instances: '0',
        collection_min: '794',
        last_collection_end: '2018-04-25 21:02:11.2511071419 +0000',
        missed_collections_send_bytes: '19446',
        count_avg: '3346',
        sensor_path_collection:
          'Cisco-IOS-XR-shellutil-filesystem-oper:file-system/node',
        missed_collections: '3'
      }
    ],
    sub7: [
      {
        count_max: '100',
        item_count_status: 'Active',
        method: 'DATALIST',
        collection_max: '100',
        item_count: '141',
        sysdb_path:
          '/oper/ipv4-rib/gl/vrf/*/afi/*/safi/*/table/*/route/*,*,*,*',
        total_send_errors: '0',
        last_collection_start: '2018-04-25 21:02:26.2526239419 +0000',
        total_min: '42',
        collection_interval: '10000',
        count: '14',
        total_other_errors: '0',
        total_avg: '62',
        num_collection: '14',
        encoding_collection: 'self-describing-gpb',
        total_max: '106',
        missed_collections_dropped_bytes: '0',
        missed_collections_send_packets: '14',
        collection_id: '16',
        total_deferred: '0',
        count_min: '38',
        total_send_drops: '0',
        no_data_instances: '0',
        collection_min: '38',
        last_collection_end: '2018-04-25 21:02:26.2526307419 +0000',
        missed_collections_send_bytes: '302466',
        count_avg: '58',
        sensor_path_collection:
          'Cisco-IOS-XR-ip-rib-ipv4-oper:rib/vrfs/vrf/afs/af/safs/saf/ip-rib-route-table-names/ip-rib-route-table-name/routes/route',
        missed_collections: '0'
      }
    ],
    sub6: [
      {
        count_max: '11',
        item_count_status: 'Active',
        method: 'GET',
        collection_max: '11',
        item_count: '14',
        sysdb_path: '/oper/inventory/gl/rack/*/attrib/inv_basic_bag',
        total_send_errors: '0',
        last_collection_start: '2018-04-25 21:02:15.2515496419 +0000',
        total_min: '5',
        collection_interval: '10000',
        count: '13',
        total_other_errors: '0',
        total_avg: '8',
        num_collection: '13',
        encoding_collection: 'self-describing-gpb',
        total_max: '11',
        missed_collections_dropped_bytes: '0',
        missed_collections_send_packets: '13',
        collection_id: '14',
        total_deferred: '0',
        count_min: '5',
        total_send_drops: '0',
        no_data_instances: '0',
        collection_min: '5',
        last_collection_end: '2018-04-25 21:02:15.2515507419 +0000',
        missed_collections_send_bytes: '8432',
        count_avg: '8',
        sensor_path_collection:
          'Cisco-IOS-XR-invmgr-oper:inventory/racks/rack/attributes/inv-basic-bag',
        missed_collections: '0'
      }
    ],
    sub3: [
      {
        count_max: '79',
        item_count_status: 'Active',
        method: 'DATALIST',
        collection_max: '142',
        item_count: '807',
        sysdb_path: '/oper/stats/ifg/*/latest/proto/*',
        total_send_errors: '0',
        last_collection_start: '2018-04-25 21:02:17.2517137419 +0000',
        total_min: '117',
        collection_interval: '10000',
        count: '13',
        total_other_errors: '0',
        total_avg: '136',
        num_collection: '13',
        encoding_collection: 'self-describing-gpb',
        total_max: '163',
        missed_collections_dropped_bytes: '0',
        missed_collections_send_packets: '13',
        collection_id: '18',
        total_deferred: '0',
        count_min: '60',
        total_send_drops: '0',
        no_data_instances: '13',
        collection_min: '101',
        last_collection_end: '2018-04-25 21:02:17.2517274419 +0000',
        missed_collections_send_bytes: '245352',
        count_avg: '67',
        sensor_path_collection:
          'Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest',
        missed_collections: '0'
      }
    ],
    sub2: [
      {
        count_max: '34',
        item_count_status: 'Active',
        method: 'GET',
        collection_max: '196',
        item_count: '27',
        sysdb_path: '/oper/mpls_fwd/node/*/fwding_summary',
        total_send_errors: '0',
        last_collection_start: '2018-04-25 21:02:18.2518506419 +0000',
        total_min: '216',
        collection_interval: '10000',
        count: '13',
        total_other_errors: '28',
        total_avg: '244',
        num_collection: '14',
        encoding_collection: 'self-describing-gpb',
        total_max: '347',
        missed_collections_dropped_bytes: '0',
        missed_collections_send_packets: '13',
        collection_id: '4',
        total_deferred: '0',
        count_min: '22',
        total_send_drops: '0',
        no_data_instances: '14',
        collection_min: '139',
        last_collection_end: '2018-04-25 21:02:19.2518731419 +0000',
        missed_collections_send_bytes: '25138',
        count_avg: '28',
        sensor_path_collection:
          'Cisco-IOS-XR-fib-common-oper:mpls-forwarding/nodes/node',
        missed_collections: '0'
      }
    ],
    sub1: [
      {
        count_max: '50',
        item_count_status: 'Active',
        method: 'DATALIST',
        collection_max: '50',
        item_count: '316',
        sysdb_path: '/oper/fib/node/*/protocol/*/summary/*,*',
        total_send_errors: '0',
        last_collection_start: '2018-04-25 21:02:36.2535973419 +0000',
        total_min: '37',
        collection_interval: '10000',
        count: '15',
        total_other_errors: '0',
        total_avg: '42',
        num_collection: '15',
        encoding_collection: 'self-describing-gpb',
        total_max: '52',
        missed_collections_dropped_bytes: '0',
        missed_collections_send_packets: '15',
        collection_id: '13',
        total_deferred: '0',
        count_min: '36',
        total_send_drops: '0',
        no_data_instances: '0',
        collection_min: '36',
        last_collection_end: '2018-04-25 21:02:36.2536011419 +0000',
        missed_collections_send_bytes: '969655',
        count_avg: '41',
        sensor_path_collection:
          'Cisco-IOS-XR-fib-common-oper:fib/nodes/node/protocols/protocol/fib-summaries/fib-summary',
        missed_collections: '0'
      }
    ],
    sub14: [
      {
        count_max: '434',
        item_count_status: 'Active',
        method: 'DATALIST',
        collection_max: '434',
        item_count: '40',
        sysdb_path: '/oper/wdsysmon_fd/gl/*',
        total_send_errors: '0',
        last_collection_start: '2018-04-25 21:02:20.2520337419 +0000',
        total_min: '343',
        collection_interval: '10000',
        count: '13',
        total_other_errors: '0',
        total_avg: '394',
        num_collection: '13',
        encoding_collection: 'self-describing-gpb',
        total_max: '436',
        missed_collections_dropped_bytes: '0',
        missed_collections_send_packets: '26',
        collection_id: '10',
        total_deferred: '0',
        count_min: '342',
        total_send_drops: '0',
        no_data_instances: '0',
        collection_min: '342',
        last_collection_end: '2018-04-25 21:02:21.2520773419 +0000',
        missed_collections_send_bytes: '2129934',
        count_avg: '392',
        sensor_path_collection:
          'Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization',
        missed_collections: '0'
      }
    ],
    sub8: [
      {
        count_max: '31',
        item_count_status: 'Active',
        method: 'DATALIST',
        collection_max: '31',
        item_count: '155',
        sysdb_path: '/oper/ipv4-rib/gl/table/*/summary/*',
        total_send_errors: '0',
        last_collection_start: '2018-04-25 21:02:25.2525641419 +0000',
        total_min: '14',
        collection_interval: '10000',
        count: '14',
        total_other_errors: '0',
        total_avg: '17',
        num_collection: '14',
        encoding_collection: 'self-describing-gpb',
        total_max: '31',
        missed_collections_dropped_bytes: '0',
        missed_collections_send_packets: '14',
        collection_id: '21',
        total_deferred: '0',
        count_min: '13',
        total_send_drops: '0',
        no_data_instances: '0',
        collection_min: '13',
        last_collection_end: '2018-04-25 21:02:25.2525655419 +0000',
        missed_collections_send_bytes: '322625',
        count_avg: '16',
        sensor_path_collection:
          'Cisco-IOS-XR-ip-rib-ipv4-oper:rib/rib-table-ids/rib-table-id/summary-protos/summary-proto',
        missed_collections: '0'
      }
    ],
    sub5: [
      {
        count_max: '1480',
        item_count_status: 'Active',
        method: 'GET',
        collection_max: '1567',
        item_count: '5589',
        sysdb_path: '/oper/inventory/gl/entity/*/attrib/inv_basic_bag',
        total_send_errors: '0',
        last_collection_start: '2018-04-25 21:02:21.2521034419 +0000',
        total_min: '2447',
        collection_interval: '10000',
        count: '11',
        total_other_errors: '0',
        total_avg: '2565',
        num_collection: '11',
        encoding_collection: 'self-describing-gpb',
        total_max: '2714',
        missed_collections_dropped_bytes: '0',
        missed_collections_send_packets: '55',
        collection_id: '1',
        total_deferred: '11',
        count_min: '1292',
        total_send_drops: '0',
        no_data_instances: '11',
        collection_min: '1373',
        last_collection_end: '2018-04-25 21:02:23.2523622419 +0000',
        missed_collections_send_bytes: '3001341',
        count_avg: '1366',
        sensor_path_collection:
          'Cisco-IOS-XR-invmgr-oper:inventory/entities/entity',
        missed_collections: '2'
      }
    ],
    sub20: [
      {
        count_max: '9',
        item_count_status: 'Active',
        method: 'DATALIST',
        collection_max: '39',
        item_count: '13',
        sysdb_path: '/oper/ipv4_arm/gl/active/db/vrf/*/net/*,*,*',
        total_send_errors: '0',
        last_collection_start: '2018-04-25 21:02:06.2506054419 +0000',
        total_min: '35',
        collection_interval: '10000',
        count: '12',
        total_other_errors: '0',
        total_avg: '56',
        num_collection: '13',
        encoding_collection: 'self-describing-gpb',
        total_max: '84',
        missed_collections_dropped_bytes: '0',
        missed_collections_send_packets: '12',
        collection_id: '15',
        total_deferred: '0',
        count_min: '4',
        total_send_drops: '0',
        no_data_instances: '37',
        collection_min: '15',
        last_collection_end: '2018-04-25 21:02:06.2506108419 +0000',
        missed_collections_send_bytes: '5839',
        count_avg: '6',
        sensor_path_collection: 'Cisco-IOS-XR-ip-iarm-v4-oper:ipv4arm',
        missed_collections: '0'
      }
    ],
    sub12: [
      {
        count_max: '15007',
        item_count_status: 'Active',
        method: 'DATALIST',
        collection_max: '15007',
        item_count: '4010',
        sysdb_path: '/oper/processmemory_linux/node/*/proc/*',
        total_send_errors: '0',
        last_collection_start: '2018-04-25 21:02:25.2525612419 +0000',
        total_min: '14948',
        collection_interval: '10000',
        count: '5',
        total_other_errors: '0',
        total_avg: '14980',
        num_collection: '5',
        encoding_collection: 'self-describing-gpb',
        total_max: '15011',
        missed_collections_dropped_bytes: '0',
        missed_collections_send_packets: '15',
        collection_id: '7',
        total_deferred: '0',
        count_min: '14944',
        total_send_drops: '0',
        no_data_instances: '0',
        collection_min: '14944',
        last_collection_end: '2018-04-25 21:02:15.2515611419 +0000',
        missed_collections_send_bytes: '982382',
        count_avg: '14975',
        sensor_path_collection:
          'Cisco-IOS-XR-procmem-oper:processes-memory/nodes/node/process-ids/process-id',
        missed_collections: '8'
      }
    ],
    sub19: [
      {
        count_max: '7',
        item_count_status: 'Active',
        method: 'DATALIST',
        collection_max: '7',
        item_count: '309',
        sysdb_path: '/oper/ipv4-arp/node/*/entry/*,*',
        total_send_errors: '0',
        last_collection_start: '2018-04-25 21:02:25.2525614419 +0000',
        total_min: '17',
        collection_interval: '10000',
        count: '14',
        total_other_errors: '0',
        total_avg: '19',
        num_collection: '14',
        encoding_collection: 'self-describing-gpb',
        total_max: '24',
        missed_collections_dropped_bytes: '0',
        missed_collections_send_packets: '14',
        collection_id: '11',
        total_deferred: '0',
        count_min: '3',
        total_send_drops: '0',
        no_data_instances: '14',
        collection_min: '3',
        last_collection_end: '2018-04-25 21:02:25.2525634419 +0000',
        missed_collections_send_bytes: '80611',
        count_avg: '5',
        sensor_path_collection:
          'Cisco-IOS-XR-ipv4-arp-oper:arp/nodes/node/entries/entry',
        missed_collections: '0'
      }
    ],
    sub0: [
      {
        count_max: '16',
        item_count_status: 'Active',
        method: 'GET',
        collection_max: '16',
        item_count: '43',
        sysdb_path: '/oper/fib-statistics/node/*/drops/c',
        total_send_errors: '0',
        last_collection_start: '2018-04-25 21:02:25.2525557419 +0000',
        total_min: '11',
        collection_interval: '10000',
        count: '14',
        total_other_errors: '0',
        total_avg: '13',
        num_collection: '14',
        encoding_collection: 'self-describing-gpb',
        total_max: '16',
        missed_collections_dropped_bytes: '0',
        missed_collections_send_packets: '14',
        collection_id: '12',
        total_deferred: '0',
        count_min: '11',
        total_send_drops: '0',
        no_data_instances: '0',
        collection_min: '11',
        last_collection_end: '2018-04-25 21:02:25.2525568419 +0000',
        missed_collections_send_bytes: '33819',
        count_avg: '13',
        sensor_path_collection:
          'Cisco-IOS-XR-fib-common-oper:fib-statistics/nodes/node/drops',
        missed_collections: '0'
      }
    ],
    sub11: [
      {
        count_max: '6866',
        item_count_status: 'Active',
        method: 'GET',
        collection_max: '6866',
        item_count: '34',
        sysdb_path: '/oper/showd/node/*/show_mem_detail',
        total_send_errors: '0',
        last_collection_start: '2018-04-25 21:02:30.2530696419 +0000',
        total_min: '2310',
        collection_interval: '10000',
        count: '11',
        total_other_errors: '0',
        total_avg: '2837',
        num_collection: '11',
        encoding_collection: 'self-describing-gpb',
        total_max: '6866',
        missed_collections_dropped_bytes: '0',
        missed_collections_send_packets: '11',
        collection_id: '3',
        total_deferred: '0',
        count_min: '2310',
        total_send_drops: '0',
        no_data_instances: '0',
        collection_min: '2310',
        last_collection_end: '2018-04-25 21:02:33.2533049419 +0000',
        missed_collections_send_bytes: '109678',
        count_avg: '2837',
        sensor_path_collection:
          'Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/detail',
        missed_collections: '3'
      }
    ],
    sub17: [
      {
        count_max: '',
        item_count_status: 'Active',
        method: '',
        collection_max: '9',
        item_count: '0',
        sysdb_path: '/oper/ipv6-ma/node/*/if/vrf/*/1/ifbrief/*',
        total_send_errors: '0',
        last_collection_start: '2018-04-25 21:02:05.2505450419 +0000',
        total_min: '7',
        collection_interval: '10000',
        count: '',
        total_other_errors: '0',
        total_avg: '10',
        num_collection: '13',
        encoding_collection: 'self-describing-gpb',
        total_max: '24',
        missed_collections_dropped_bytes: '0',
        missed_collections_send_packets: '0',
        collection_id: '5',
        total_deferred: '0',
        count_min: '',
        total_send_drops: '0',
        no_data_instances: '13',
        collection_min: '1',
        last_collection_end: '2018-04-25 21:02:05.2505459419 +0000',
        missed_collections_send_bytes: '0',
        count_avg: '',
        sensor_path_collection:
          'Cisco-IOS-XR-ipv6-ma-oper:ipv6-network/nodes/node/interface-data/vrfs/vrf/briefs/brief',
        missed_collections: '0'
      }
    ],
    sub16: [
      {
        count_max: '7',
        item_count_status: 'Active',
        method: 'DATALIST',
        collection_max: '7',
        item_count: '92',
        sysdb_path: '/oper/intf_mgbl/gl/brief/*',
        total_send_errors: '0',
        last_collection_start: '2018-04-25 21:02:15.2515662419 +0000',
        total_min: '3',
        collection_interval: '10000',
        count: '13',
        total_other_errors: '0',
        total_avg: '4',
        num_collection: '13',
        encoding_collection: 'self-describing-gpb',
        total_max: '7',
        missed_collections_dropped_bytes: '0',
        missed_collections_send_packets: '13',
        collection_id: '17',
        total_deferred: '0',
        count_min: '3',
        total_send_drops: '0',
        no_data_instances: '0',
        collection_min: '3',
        last_collection_end: '2018-04-25 21:02:15.2515665419 +0000',
        missed_collections_send_bytes: '40737',
        count_avg: '4',
        sensor_path_collection:
          'Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-briefs/interface-brief',
        missed_collections: '0'
      }
    ],
    sub18: [
      {
        count_max: '',
        item_count_status: 'Active',
        method: '',
        collection_max: '14',
        item_count: '0',
        sysdb_path: '/oper/ipv6-nd/node/*/cache/interfaces/*/*,*,*,*',
        total_send_errors: '0',
        last_collection_start: '2018-04-25 21:02:35.2535550419 +0000',
        total_min: '8',
        collection_interval: '10000',
        count: '',
        total_other_errors: '0',
        total_avg: '10',
        num_collection: '16',
        encoding_collection: 'self-describing-gpb',
        total_max: '14',
        missed_collections_dropped_bytes: '0',
        missed_collections_send_packets: '0',
        collection_id: '20',
        total_deferred: '0',
        count_min: '',
        total_send_drops: '0',
        no_data_instances: '0',
        collection_min: '8',
        last_collection_end: '2018-04-25 21:02:35.2535560419 +0000',
        missed_collections_send_bytes: '0',
        count_avg: '',
        sensor_path_collection:
          'Cisco-IOS-XR-ipv6-nd-oper:ipv6-node-discovery/nodes/node/neighbor-interfaces/neighbor-interface/host-addresses/host-address',
        missed_collections: '0'
      }
    ],
    sub9: [
      {
        count_max: '53',
        item_count_status: 'Active',
        method: 'DATALIST',
        collection_max: '53',
        item_count: '76',
        sysdb_path: '/oper/ipv4-rib/gl/table/*/interface/*/*',
        total_send_errors: '0',
        last_collection_start: '2018-04-25 21:02:36.2535895419 +0000',
        total_min: '26',
        collection_interval: '10000',
        count: '15',
        total_other_errors: '0',
        total_avg: '33',
        num_collection: '15',
        encoding_collection: 'self-describing-gpb',
        total_max: '53',
        missed_collections_dropped_bytes: '0',
        missed_collections_send_packets: '15',
        collection_id: '19',
        total_deferred: '0',
        count_min: '25',
        total_send_drops: '0',
        no_data_instances: '0',
        collection_min: '25',
        last_collection_end: '2018-04-25 21:02:36.2535922419 +0000',
        missed_collections_send_bytes: '148000',
        count_avg: '32',
        sensor_path_collection:
          'Cisco-IOS-XR-ip-rib-ipv4-oper:rib/rib-table-ids/rib-table-id/rib-table-itf-hndls/rib-table-itf-hndl/itf-route',
        missed_collections: '0'
      }
    ]
  };
  app.get('/api/subscriptions', (req, res) => {
    res.status(200).send(values);
  });
};
